/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpDialog.java
 *
 * Created on 4.12.2010, 14:13:32
 */

package cz.wt.convertor.exceltopdf.dialogs;

import javax.swing.JDialog;

/**
 *
 * @author forrest
 */
public class HelpDialog extends JDialog {

    /** Creates new form HelpDialog */
    public HelpDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
//        getRootPane().setDefaultButton(closeButton);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("HelpBox"); // NOI18N
        setResizable(false);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
