// $Id$
// Klasifikace: CHRÁNÌNÉ
package cz.wt.convertor.main.gui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author diblik
 * @version $Revision$
 */
public class WorkingFrame extends JFrame {

  /** Creates new form WorkingFrame */
  public WorkingFrame() {
    initComponents();
    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/working5.gif")); //Animated gif
    jLabel1.setIcon(icon);
    setSize(92,40);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setAlwaysOnTop(true);
    setUndecorated(true);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel1.setName("jPanel1"); // NOI18N
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText(" pracuji...");
    jLabel1.setName("jLabel1"); // NOI18N
    jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jPanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
