package cz.wt.convertor.main.gui;

import javax.swing.JFrame;

/**
 *
 * @author diblik
 * @version $Revision$
 */
public class HelpFrame extends JFrame {

  /** Creates new form HelpFrame */
  public HelpFrame() {
    initComponents();
    setSize(500, 400);
    jTextArea1.setEditable(false);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setTitle("Nápovìda");
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("Pro správný bìh programu je nutné splòit násedující:\n1. Vytvoøit excel soubor a ukládat jej jen v režimu kompatibility (97-2003).\n\n2. Excel soubor bude mít dvì záložky. První pro data, druhá pro parametry.\n\n3. Záložka pro data (první založka) bude obsahovat sloupce s headerem (první buòka sloupce), který bude obsahovat název sloupce nejlépe bez diakritiky (dùležité pro další použití).\n\n4. Sloupcù mùže být libovolné množství a pod headerem se mùže náchazet libovolné množství øádkù. každá buòka pod hederem nemusí být vyplòená.\n\n5. Záložka pro parametry (druhá záložka) je volitelná. Pokud existuje musí obsahovat dva sloupce s headerem: parametr-jmeno, parametr-hodnota. Kde sloupec parametr-jmeno obsahuje konkrétní jmeno parametru a sloupec parametr-hodnota obsahuje konkrétní hodnotu parametru.\n\n6. Pomocí programu iReport (stáhnout zde: http://jasperforge.org/projects/ireport) vytvoøíme šablonu. Šablona definuje jak pøesne se rozmístí jednotlivé buòky z excel souboru.\n\n7. Na šablonu umístíme \"fieldy (Fileds)\", které pojmenujeme stejnì jako jednotlivé sloupce v excel záložce pro data (první záložka) a \"parametry (Parameters)\", které opìt pojmenujeme stejnì jako jsou jednotlivé buòky v záložce pro parametry (druhá záložka) ve sloupci s nazvem \"parametr-jmeno\".\n\n8. Každá šablona reprezentuje jeden øádek v záložce pro data. Tedy více øádkù znamená více stránek s rozložením dle definované šablony. Kde každá stránka má data dle daného øádku v excel souboru. Jen paramtry se opakují pro každou stránku (napø. pro datum, které je poøád stejné)\n\n");
    jTextArea1.setName("jTextArea1"); // NOI18N
    jScrollPane1.setViewportView(jTextArea1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jScrollPane1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
